regla1: Almacenamiento.o Conversacion.o ConversacionController.o ConversacionFactory.o DtContacto.o DtConversacion.o DtGrupo.o DtImagen.o DtMensaje.o DtParticipante.o DtPrivada.o DtReceptor.o DtSimple.o DtTarjetaContacto.o DtVideo.o Estado.o Fecha.o FechaHora.o Grupo.o Imagen.o ManejadorUsuario.o Mensaje.o MensajeController.o MensajeFactory.o Multimedia.o Privada.o Sesion.o Simple.o TarjetaContacto.o Usuario.o UsuarioController.o UsuarioConversacion.o UsuarioFactory.o UsuarioMensaje.o Video.o main.o
	g++ -I./include/ -Wall -o programa Almacenamiento.o Conversacion.o ConversacionController.o ConversacionFactory.o DtContacto.o DtConversacion.o DtGrupo.o DtImagen.o DtMensaje.o DtParticipante.o DtPrivada.o DtReceptor.o DtSimple.o DtTarjetaContacto.o DtVideo.o Estado.o Fecha.o FechaHora.o Grupo.o Imagen.o ManejadorUsuario.o Mensaje.o MensajeController.o MensajeFactory.o Multimedia.o Privada.o Sesion.o Simple.o TarjetaContacto.o Usuario.o UsuarioController.o UsuarioConversacion.o UsuarioFactory.o UsuarioMensaje.o Video.o main.o

Almacenamiento.o: src/Almacenamiento.cpp
	g++ -I./include/ -Wall -c src/Almacenamiento.cpp -o Almacenamiento.o

Conversacion.o: src/Conversacion.cpp
	g++ -I./include/ -Wall -c src/Conversacion.cpp -o Conversacion.o
	
ConversacionController.o: src/ConversacionController.cpp
	g++ -I./include/ -Wall -c src/ConversacionController.cpp -o ConversacionController.o
	
ConversacionFactory.o: src/ConversacionFactory.cpp
	g++ -I./include/ -Wall -c src/ConversacionFactory.cpp -o ConversacionFactory.o
	
DtContacto.o: src/DtContacto.cpp
	g++ -I./include/ -Wall -c src/DtContacto.cpp -o DtContacto.o
	
DtConversacion.o: src/DtConversacion.cpp
	g++ -I./include/ -Wall -c src/DtConversacion.cpp -o DtConversacion.o
	
DtGrupo.o: src/DtGrupo.cpp
	g++ -I./include/ -Wall -c src/DtGrupo.cpp -o DtGrupo.o

DtImagen.o: src/DtImagen.cpp
	g++ -I./include/ -Wall -c src/DtImagen.cpp -o DtImagen.o
	
DtMensaje.o: src/DtMensaje.cpp
	g++ -I./include/ -Wall -c src/DtMensaje.cpp -o DtMensaje.o
	
DtParticipante.o: src/DtParticipante.cpp
	g++ -I./include/ -Wall -c src/DtParticipante.cpp -o DtParticipante.o
	
DtPrivada.o: src/DtPrivada.cpp
	g++ -I./include/ -Wall -c src/DtPrivada.cpp -o DtPrivada.o
	
DtReceptor.o: src/DtReceptor.cpp
	g++ -I./include/ -Wall -c src/DtReceptor.cpp -o DtReceptor.o
	
DtSimple.o: src/DtSimple.cpp
	g++ -I./include/ -Wall -c src/DtSimple.cpp -o DtSimple.o
	
DtTarjetaContacto.o: src/DtTarjetaContacto.cpp
	g++ -I./include/ -Wall -c src/DtTarjetaContacto.cpp -o DtTarjetaContacto.o
	
DtVideo.o: src/DtVideo.cpp
	g++ -I./include/ -Wall -c src/DtVideo.cpp -o DtVideo.o
	
Estado.o: src/Estado.cpp
	g++ -I./include/ -Wall -c src/Estado.cpp -o Estado.o
	
Fecha.o: src/Fecha.cpp
	g++ -I./include/ -Wall -c src/Fecha.cpp -o Fecha.o
	
FechaHora.o: src/FechaHora.cpp
	g++ -I./include/ -Wall -c src/FechaHora.cpp -o FechaHora.o
	
Grupo.o: src/Grupo.cpp
	g++ -I./include/ -Wall -c src/Grupo.cpp -o Grupo.o
	
Imagen.o: src/Imagen.cpp
	g++ -I./include/ -Wall -c src/Imagen.cpp -o Imagen.o
	
ManejadorUsuario.o: src/ManejadorUsuario.cpp
	g++ -I./include/ -Wall -c src/ManejadorUsuario.cpp -o ManejadorUsuario.o
	
Mensaje.o: src/Mensaje.cpp
	g++ -I./include/ -Wall -c src/Mensaje.cpp -o Mensaje.o
	
MensajeController.o: src/MensajeController.cpp
	g++ -I./include/ -Wall -c src/MensajeController.cpp -o MensajeController.o
	
MensajeFactory.o: src/MensajeFactory.cpp
	g++ -I./include/ -Wall -c src/MensajeFactory.cpp -o MensajeFactory.o
	
Multimedia.o: src/Multimedia.cpp
	g++ -I./include/ -Wall -c src/Multimedia.cpp -o Multimedia.o
	
Privada.o: src/Privada.cpp
	g++ -I./include/ -Wall -c src/Privada.cpp -o Privada.o
	
Sesion.o: src/Sesion.cpp
	g++ -I./include/ -Wall -c src/Sesion.cpp -o Sesion.o
	
Simple.o: src/Simple.cpp
	g++ -I./include/ -Wall -c src/Simple.cpp -o Simple.o
	
TarjetaContacto.o: src/TarjetaContacto.cpp
	g++ -I./include/ -Wall -c src/TarjetaContacto.cpp -o TarjetaContacto.o
	
Usuario.o: src/Usuario.cpp
	g++ -I./include/ -Wall -c src/Usuario.cpp -o Usuario.o
	
UsuarioController.o: src/UsuarioController.cpp
	g++ -I./include/ -Wall -c src/UsuarioController.cpp -o UsuarioController.o
	
UsuarioConversacion.o: src/UsuarioConversacion.cpp
	g++ -I./include/ -Wall -c src/UsuarioConversacion.cpp -o UsuarioConversacion.o
	
UsuarioFactory.o: src/UsuarioFactory.cpp
	g++ -I./include/ -Wall -c src/UsuarioFactory.cpp -o UsuarioFactory.o
	
UsuarioMensaje.o: src/UsuarioMensaje.cpp
	g++ -I./include/ -Wall -c src/UsuarioMensaje.cpp -o UsuarioMensaje.o
	
Video.o: src/Video.cpp
	g++ -I./include/ -Wall -c src/Video.cpp -o Video.o
	
main.o: main.cpp
	g++ -I./include/ -Wall -c main.cpp -o main.o